# Generated by Django 2.2.1 on 2019-07-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_name', models.CharField(max_length=164, verbose_name='Private name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_name', models.CharField(max_length=164, verbose_name='Private name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemI18n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164, verbose_name='Name i18n')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.Item')),
            ],
            options={
                'verbose_name': 'Item i18n',
                'verbose_name_plural': 'Items i18n',
            },
        ),
        migrations.CreateModel(
            name='CategoryI18n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=164, verbose_name='Name i18n')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='basic_app.Category')),
            ],
            options={
                'verbose_name': 'Category i18n',
                'verbose_name_plural': 'Categories i18n',
            },
        ),
    ]
